"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { getActiveTenant } from "@/lib/tenant-context";
import RecipeBuilder from "@/components/RecipeBuilder";

const euro = (n:number) => new Intl.NumberFormat("en-IE", { style:"currency", currency:"EUR" }).format(n||0);
const fmt = (n:number) => new Intl.NumberFormat("en-IE", { maximumFractionDigits:3 }).format(n||0);
const unitLabel:Record<string,string> = { KG:"kg", G:"g", L:"L", ML:"ml", PCS:"pcs" };

export default function InventoryDashboard(){
 const slug=typeof window!=="undefined"?getActiveTenant():""; const [data,setData]=useState<any>(null); const [tab,setTab]=useState("ingredients"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [search,setSearch]=useState("");
 const load=async()=>{ const r=await fetch(`/api/restaurants/${slug}/inventory`,{cache:"no-store"}); const j=await r.json(); if(!r.ok) throw new Error(j.error); setData(j); };
 useEffect(()=>{ if(slug) load().catch(e=>setError(e.message)); },[slug]);
 const submit=async(e:FormEvent<HTMLFormElement>,action:string)=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const payload:any={action};f.forEach((v,k)=>payload[k]=v);["currentStock","minimumStock","reorderLevel","costPerUnit","leadTimeDays","quantity"].forEach(k=>{if(k in payload)payload[k]=Number(payload[k])});try{const r=await fetch(`/api/restaurants/${slug}/inventory`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error);e.currentTarget.reset();await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const filtered=useMemo(()=>data?.ingredients.filter((i:any)=>`${i.name} ${i.category} ${i.supplier?.name||""}`.toLowerCase().includes(search.toLowerCase()))||[],[data,search]);
 if(!data)return <main className="inventoryShell"><p>{error||"Loading inventory…"}</p></main>;
 return <main className="inventoryShell"><header className="inventoryHeader"><div><span className="inventoryEyebrow">OPERATIONS HUB</span><h1>Inventory</h1><p>Control stock, suppliers and every adjustment for {data.restaurantName}.</p></div><nav><Link href={`/r/${slug}/admin`}>Admin</Link><Link href={`/r/${slug}/marketing`}>Marketing</Link><Link href={`/r/${slug}/analytics`}>Analytics</Link></nav></header>{error&&<div className="inventoryError">{error}</div>}
 <section className="inventoryStats"><article><small>Ingredients</small><strong>{data.summary.ingredients}</strong></article><article><small>Suppliers</small><strong>{data.summary.suppliers}</strong></article><article className={data.summary.lowStock?"warn":""}><small>Low stock</small><strong>{data.summary.lowStock}</strong></article><article className={data.summary.outOfStock?"danger":""}><small>Out of stock</small><strong>{data.summary.outOfStock}</strong></article><article><small>Inventory value</small><strong>{euro(data.summary.inventoryValue)}</strong></article></section>
 <nav className="inventoryTabs">{[["ingredients","Ingredients"],["recipes","Recipes & costing"],["suppliers","Suppliers"],["movements","Stock movements"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</nav>
 {tab==="ingredients"&&<><section className="inventoryGrid"><article className="inventoryCard"><span className="inventoryEyebrow">ADD INGREDIENT</span><h2>New stock item</h2><form className="inventoryForm" onSubmit={e=>submit(e,"ingredient")}><input name="name" placeholder="Ingredient name" required/><div><input name="category" placeholder="Category e.g. Meat" required/><select name="unit"><option value="KG">kg</option><option value="G">g</option><option value="L">L</option><option value="ML">ml</option><option value="PCS">pcs</option></select></div><div><input name="currentStock" type="number" min="0" step="0.001" placeholder="Opening stock"/><input name="costPerUnit" type="number" min="0" step="0.0001" placeholder="Cost per unit €"/></div><div><input name="minimumStock" type="number" min="0" step="0.001" placeholder="Minimum stock"/><input name="reorderLevel" type="number" min="0" step="0.001" placeholder="Reorder level"/></div><select name="supplierId"><option value="">No supplier</option>{data.suppliers.filter((s:any)=>s.active).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button disabled={busy}>Add ingredient</button></form></article><article className="inventoryCard"><span className="inventoryEyebrow">STOCK ADJUSTMENT</span><h2>Record movement</h2><form className="inventoryForm" onSubmit={e=>submit(e,"movement")}><select name="ingredientId" required><option value="">Choose ingredient</option>{data.ingredients.filter((i:any)=>i.active).map((i:any)=><option key={i.id} value={i.id}>{i.name} · {fmt(i.currentStock)} {unitLabel[i.unit]}</option>)}</select><select name="type"><option value="RECEIVED">Stock received</option><option value="ADJUSTMENT">Manual adjustment (+ or -)</option><option value="WASTE">Waste</option></select><input name="quantity" type="number" step="0.001" placeholder="Quantity" required/><input name="reason" placeholder="Reason or delivery reference"/><button disabled={busy}>Record movement</button></form></article></section><section className="inventoryCard"><div className="inventorySectionHead"><div><span className="inventoryEyebrow">STOCK LIST</span><h2>Ingredients</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search stock…"/></div><div className="inventoryTable"><div className="inventoryRow inventoryTableHead"><span>Ingredient</span><span>Stock</span><span>Status</span><span>Cost</span><span>Value</span><span>Supplier</span></div>{filtered.map((i:any)=>{const status=i.currentStock<=0?"Out":i.currentStock<=i.reorderLevel?"Low":"Healthy";return <div className="inventoryRow" key={i.id}><span><b>{i.name}</b><small>{i.category}</small></span><span>{fmt(i.currentStock)} {unitLabel[i.unit]}</span><span><i className={`stockBadge ${status.toLowerCase()}`}>{status}</i></span><span>{euro(i.costPerUnit)}/{unitLabel[i.unit]}</span><span>{euro(i.currentStock*i.costPerUnit)}</span><span>{i.supplier?.name||"—"}</span></div>})}</div></section></>}
 {tab==="recipes"&&<RecipeBuilder data={data} reload={load}/>}
 {tab==="suppliers"&&<section className="inventoryGrid"><article className="inventoryCard"><span className="inventoryEyebrow">ADD SUPPLIER</span><h2>New supplier</h2><form className="inventoryForm" onSubmit={e=>submit(e,"supplier")}><input name="name" placeholder="Supplier business name" required/><input name="contactName" placeholder="Contact person"/><div><input name="email" type="email" placeholder="Email"/><input name="phone" placeholder="Phone"/></div><input name="leadTimeDays" type="number" min="0" placeholder="Lead time in days"/><textarea name="notes" placeholder="Notes"/><button disabled={busy}>Add supplier</button></form></article><article className="inventoryCard"><span className="inventoryEyebrow">SUPPLIER DIRECTORY</span><h2>{data.suppliers.length} suppliers</h2><div className="supplierList">{data.suppliers.map((s:any)=><div key={s.id}><b>{s.name}</b><span>{s.contactName||"No contact"}</span><small>{s.email||s.phone||"No contact details"} · {s.leadTimeDays} day lead time · {s._count.ingredients} ingredients</small></div>)}</div></article></section>}
 {tab==="movements"&&<section className="inventoryCard"><span className="inventoryEyebrow">AUDIT TRAIL</span><h2>Latest stock movements</h2><div className="inventoryTable movements"><div className="inventoryRow inventoryTableHead"><span>Date</span><span>Ingredient</span><span>Type</span><span>Change</span><span>Balance</span><span>Reason</span></div>{data.movements.map((m:any)=><div className="inventoryRow" key={m.id}><span>{new Date(m.createdAt).toLocaleString("en-IE")}</span><span><b>{m.ingredient.name}</b></span><span>{m.type.replaceAll("_"," ")}</span><span className={m.quantity<0?"negative":"positive"}>{m.quantity>0?"+":""}{fmt(m.quantity)} {unitLabel[m.ingredient.unit]}</span><span>{fmt(m.balanceAfter)} {unitLabel[m.ingredient.unit]}</span><span>{m.reason||"—"}<small>{m.createdBy||"System"}</small></span></div>)}</div></section>}
 </main>
}
