"use client";
import { useEffect, useMemo, useState } from "react";
import { getActiveTenant } from "@/lib/tenant-context";

const units: Record<string,string> = { KG:"kg", G:"g", L:"L", ML:"ml", PCS:"pcs" };
const euro=(n:number)=>new Intl.NumberFormat("en-IE",{style:"currency",currency:"EUR"}).format(n||0);
const convert=(q:number, from:string, to:string)=> from===to?q:from==="G"&&to==="KG"?q/1000:from==="KG"&&to==="G"?q*1000:from==="ML"&&to==="L"?q/1000:from==="L"&&to==="ML"?q*1000:NaN;

export default function RecipeBuilder({ data, reload }: { data:any; reload:()=>Promise<void> }) {
  const slug=typeof window!=="undefined"?getActiveTenant():"";
  const [menuItemId,setMenuItemId]=useState(""); const [lines,setLines]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const item=useMemo(()=>data.menuItems.find((m:any)=>m.id===menuItemId),[data,menuItemId]);
  useEffect(()=>{ if(!menuItemId&&data.menuItems[0]) setMenuItemId(data.menuItems[0].id); },[data.menuItems,menuItemId]);
  useEffect(()=>{ setLines((item?.recipeIngredients||[]).map((r:any)=>({ingredientId:r.ingredientId,quantity:r.quantity,unit:r.unit}))); setMessage(""); },[item]);
  const add=()=>{const first=data.ingredients.find((i:any)=>i.active&&!lines.some(l=>l.ingredientId===i.id));if(first)setLines([...lines,{ingredientId:first.id,quantity:1,unit:first.unit}]);};
  const update=(idx:number,patch:any)=>setLines(lines.map((l,i)=>i===idx?{...l,...patch}:l));
  const cost=lines.reduce((sum,l)=>{const ing=data.ingredients.find((i:any)=>i.id===l.ingredientId);if(!ing)return sum;const stockQty=convert(Number(l.quantity),l.unit,ing.unit);return sum+(Number.isFinite(stockQty)?stockQty*ing.costPerUnit:0)},0);
  const save=async()=>{setBusy(true);setMessage("");try{const r=await fetch(`/api/restaurants/${slug}/inventory`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"recipe",menuItemId,lines})});const j=await r.json();if(!r.ok)throw new Error(j.error);setMessage("Recipe saved successfully.");await reload();}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
  if(!data.recipeCostingEnabled)return <section className="inventoryCard recipeDisabled"><span className="inventoryEyebrow">OPTIONAL MODULE</span><h2>Recipes & automatic stock are switched off</h2><p>Enable this module in Restaurant settings. Inventory remains available without recipes.</p></section>;
  return <section className="recipeWorkspace"><article className="inventoryCard recipePicker"><span className="inventoryEyebrow">RECIPE BUILDER</span><h2>Choose a menu item</h2><select value={menuItemId} onChange={e=>setMenuItemId(e.target.value)}>{data.menuItems.map((m:any)=><option value={m.id} key={m.id}>{m.name} · {euro(m.price)}</option>)}</select><div className="recipeSummary"><span>Recipe cost<strong>{euro(cost)}</strong></span><span>Selling price<strong>{euro(item?.price||0)}</strong></span><span>Gross margin<strong>{item?.price?`${Math.max(0,(1-cost/item.price)*100).toFixed(1)}%`:"—"}</strong></span></div></article><article className="inventoryCard"><div className="inventorySectionHead"><div><span className="inventoryEyebrow">INGREDIENT BREAKDOWN</span><h2>{item?.name||"Recipe"}</h2></div><button className="recipeAdd" onClick={add}>+ Add ingredient</button></div><div className="recipeLines">{lines.length===0&&<p className="recipeEmpty">No ingredients yet. Add the first ingredient to start this recipe.</p>}{lines.map((line,idx)=>{const ing=data.ingredients.find((i:any)=>i.id===line.ingredientId);return <div className="recipeLine" key={`${line.ingredientId}-${idx}`}><select value={line.ingredientId} onChange={e=>{const selected=data.ingredients.find((i:any)=>i.id===e.target.value);update(idx,{ingredientId:e.target.value,unit:selected?.unit||"PCS"})}}>{data.ingredients.filter((i:any)=>i.active).map((i:any)=><option key={i.id} value={i.id}>{i.name}</option>)}</select><input type="number" min="0.001" step="0.001" value={line.quantity} onChange={e=>update(idx,{quantity:Number(e.target.value)})}/><select value={line.unit} onChange={e=>update(idx,{unit:e.target.value})}>{["KG","G","L","ML","PCS"].filter(u=>u===ing?.unit||(["KG","G"].includes(u)&&["KG","G"].includes(ing?.unit))||(["L","ML"].includes(u)&&["L","ML"].includes(ing?.unit))).map(u=><option key={u} value={u}>{units[u]}</option>)}</select><span>{ing?euro((convert(Number(line.quantity),line.unit,ing.unit)||0)*ing.costPerUnit):"—"}</span><button onClick={()=>setLines(lines.filter((_,i)=>i!==idx))}>×</button></div>})}</div><div className="recipeFooter"><p>{message}</p><button disabled={busy||!menuItemId} onClick={save}>{busy?"Saving…":"Save recipe"}</button></div></article></section>;
}
