"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {useParams} from "next/navigation";
type Data={restaurantName:string;generatedAt:string;period:{label:string;revenue:number;profit:number;orders:number;revenueChange:number;foodCostPercent:number};health:number;healthLabel:string;signals:{lowStock:number;outOfStock:number;atRiskCustomers:number};insights:Array<{type:string;title:string;message:string;impact:string;confidence:number;action:string;href:string}>};
const euro=(n:number)=>new Intl.NumberFormat("en-IE",{style:"currency",currency:"EUR"}).format(n);
export default function RestaurantCoach(){const {slug}=useParams<{slug:string}>();const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");const load=()=>{setError("");fetch(`/api/restaurants/${slug}/coach`,{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Could not load coach");return b}).then(setData).catch(e=>setError(e.message))};useEffect(load,[slug]);if(error)return <main style={{padding:32}}><h1>Restaurant Coach</h1><p>{error}</p><button onClick={load}>Try again</button></main>;if(!data)return <main style={{padding:32}}>Preparing your daily brief…</main>;return <main style={{maxWidth:1180,margin:"0 auto",padding:"28px 20px 60px"}}>
<div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",flexWrap:"wrap"}}><div><p style={{margin:0,color:"#6b7280",fontWeight:700}}>AI RESTAURANT COACH</p><h1 style={{fontSize:38,margin:"6px 0"}}>Good morning, {data.restaurantName} 👋</h1><p style={{color:"#6b7280",margin:0}}>Your evidence-based daily brief. Recommendations use your own restaurant data.</p></div><button onClick={load} style={{padding:"11px 16px",borderRadius:10,border:"1px solid #ddd",background:"white",fontWeight:700}}>Refresh brief</button></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:14,marginTop:26}}>{[["Revenue",euro(data.period.revenue),`${data.period.revenueChange>=0?"↑":"↓"} ${Math.abs(data.period.revenueChange).toFixed(1)}% vs prior day`],["Gross profit",euro(data.period.profit),`${data.period.foodCostPercent.toFixed(1)}% food cost`],["Orders",String(data.period.orders),data.period.label],["Restaurant health",`${data.health}/100`,data.healthLabel]].map(([a,b,c])=><section key={a} style={{background:"white",border:"1px solid #e5e7eb",borderRadius:16,padding:18,boxShadow:"0 4px 16px rgba(0,0,0,.04)"}}><div style={{color:"#6b7280",fontSize:13,fontWeight:800,textTransform:"uppercase"}}>{a}</div><div style={{fontSize:30,fontWeight:900,margin:"8px 0 3px"}}>{b}</div><div style={{fontSize:13,color:"#6b7280"}}>{c}</div></section>)}</div>
<h2 style={{marginTop:32}}>What needs your attention</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:16}}>{data.insights.map((x,i)=><article key={i} style={{background:"white",border:"1px solid #e5e7eb",borderRadius:18,padding:20,boxShadow:"0 5px 20px rgba(0,0,0,.05)"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><strong style={{fontSize:19}}>{x.title}</strong><span style={{fontSize:12,background:"#f3f4f6",padding:"5px 8px",borderRadius:20,height:"fit-content"}}>{x.confidence}% confidence</span></div><p style={{lineHeight:1.55,color:"#4b5563"}}>{x.message}</p><p style={{fontSize:13}}><b>Potential impact:</b> {x.impact}</p><Link href={x.href} style={{display:"inline-block",padding:"10px 14px",borderRadius:10,background:"#111827",color:"white",textDecoration:"none",fontWeight:800}}>{x.action} →</Link></article>)}</div>
<div style={{marginTop:24,padding:16,borderRadius:14,background:"#fff8db",border:"1px solid #f1d56b",fontSize:14}}>Coach recommendations are decision support, not automatic changes. Prices, campaigns and purchasing remain under the restaurant owner’s control.</div></main>}
